# desafio-de-carreira
modulo 01 dds18
---- MÓDULO - 01 ----

O QUE APRENDI NESTE MÓDULO:
Variáveis
Github
Como a internet funciona
Node.js
TYPESCRYPT
Comandos de git básico
LinkedIn
package json
Condicionais
Arrays e loops
Objetos

FUNCIONAMENTO DE SITES E TECNOLOGIAS INTEGRADAS PARA OTIMIZAÇÃO.
IMPORTANCIA DE UM LINKEDIN ORGANIZADO E OTIMIZADO PARA FACILITAR INTERESSE DE RECRUTADORES.
SOFT SKILLS, HABILIDADES DE PARA TRABALHO EM EQUIPE E HARMONIA EM QUALQUER ORGANIZAÇAO E ÉTICA.

Npm, node js e package json.

Alguns comandos git básicos.

Typescript que é uma linguagem de programação de tipagem estatica TypeScript é compilado para JavaScript tornando bem versatil

Metódos de arrays e loops, que são funções embutidas que podem ser usadas para manipular e iterar uma variável.

Métodos de strings, usadas para representar texto em linguagens de programação. 

O que quero aprender sobre os assuntos que serão abordados nesse módulo

APROFUNDAR NA LOGICA E CONCEITOS BASICOS DE JAVASCRIPT E TypeScript E DOMINAR COMANDOS BASICOS DE GIT.
CRIAR UM PERFIL DO LINKEDIN ATRATIVO E ENTENDER COMO APROVEITAR O POTENCIAL MAXIMO DA FERRAMENTA
ENTENDER COMO SE DIFERENCIA NO USO GERAL TypeScript DE JAVASCRIPT.
IMPORTANCIA DO GITHUB COMO PORTIFOLIO.
ETICA NA TECNOLOGIA
ENTENDER OS CONCEITOS DE VARIAVEIS, LOOP, ARRAYS, STRING 
Minha evolução: o que aprendi sobre os assuntos que foram abordados nesse módulo

APRENDI A TER UM PERFIL LINKEDIN MAIS PROFISSIONAL E ATRATATIVO, E COMO BUSCAR VAGAS DE TECNOLOGIA E COMO FAZER CONEXOES COM RECRUTADORES E PESSOAS DE INTERESSE E TER UMA REDE ATIVA.
APRENDI OS COMANDOS BASICOS DE GIT E COMO É IMPORTANTE PARA COLABORAÇAO E GERENCIAMENTO DE PROJETOS.
APRENDI CONCEITOS BASICOS DE STRING
APRENDI CONCEITOS BASICOS DE ARRAYS PARA UMA LISTA
COMO CRIAR E UTILIZAR OBJETOS COMO ESTRUTURA DE DADOS E ORGANIZAR INFORMAÇOES DE FORMA EFICIENTE 
APRENDI CONCEITOS BASICOS DE CONDICIONAIS.
